### model
model_name_or_path: /fs-computility/ai4agr/shared/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
# 当前版本增加自我认识
# 当前版本加 corn ppl filter 后的数据
### dataset
dataset: sft_com_math_light7w,sft_com_coding_5w1,sft_arabidosis_5w,sft_corn_9w_ppl_low,sft_rice_4w,sft_soybean_11w,sft_com_common_7w7,sft_com_autoif_6w,sft_com_others_7w6,sft_self_cognition_v2,sft_agr_badcase_5w
# dataset: sft_arabidosis_5w,sft_corn_9w,sft_rice_4w,sft_soybean_11w,sft_com_autoif_6w,sft_com_data_30w,sft_self_cognition_v2
template: qwen
cutoff_len: 4096
# max_samples: 1000
overwrite_cache: false
preprocessing_num_workers: 16
dataloader_num_workers: 8
streaming: false

### output
output_dir: saves/domainloss_try4/full/sft
logging_steps: 1
save_steps: -1
save_strategy: epoch

plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]
use_swanlab: true
swanlab_run_name: qwen_2_5_dataorder_light_math

### packing
packing: true
neat_packing: false
mix_strategy: concat

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 5.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
flash_attn: fa2

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
